---
title: "Final Project Code"
author: "Grace"
date: "12/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
# Load Libraries required for data analysis
library(tidyverse)
library(here)
```

# Load and Tidy Data

```{r message=FALSE}
# Load region CO2 flux dataframe
data <- read_csv(here("data/regional_survey.csv"))

# The columns of interest are AirTemp_C, and Fmmol_mmol_m2_day
## Carbon flux units are `mmol/m2/day`

# Tidy region CO2 flux dataframe
data_tidy <- data %>% mutate(Habitat = tolower(Habitat)) %>% # Change all habitat names to lowercase
  rename(c_flux = Fmmol_mmol_m2_day, # Simplify key variable names
         air_temp = AirTemp_C) %>%
  filter(air_temp >-100) %>% filter(c_flux >-100) %>% # filter out missing (-9999) values for air temp and C flux
  filter(Habitat != "tk-pond") %>% # remove tk-pond observations due to few (7) observations 
  filter(Habitat != "ocean") #remove ocean due to all equivalent air temperature values

```

## Net CO2 flux by region and by individual habitat types

```{r}
# Quantify the overall Carbon flux average (across all habitat types)
mean(data_tidy$c_flux) # Average (mmol/m2/day)
sd(data_tidy$c_flux) # Standard deviation
```

```{r}
# CO2 flux boxplot (by habitat)
ggplot()+
  geom_boxplot(data = data_tidy, mapping = aes(x= air_temp, y=(c_flux), color = Habitat)) +
  theme_bw() +
  labs(x="Habitat", y = expression(Carbon ~ Flux ~ (mmol ~ '/' ~ m^{2} ~ '/' ~ day))) 

# ANOVA, test for statistically significant difference between carbon flux by habitat
aov_cflux_hab <- aov(c_flux ~ Habitat, data = data_tidy)
summary(aov_cflux_hab) 

# Run Tukey HSD test on estimated ANOVA model
TukeyHSD(aov_cflux_hab)

# Show Tukey HSD test output
library(agricolae) # load package that helps to view output
aov_cflux_hab <- HSD.test(aov_cflux_hab, trt = "Habitat", alpha = 0.05) # set treatment variable to Habitat and p-value cutoff to 0.05
aov_cflux_hab # view output

```

## Analyze the effect of air temperature on CO2 flux (whole region)

```{r}
# Plot overall C Flux ~ Air Temperature
ggplot(data = data_tidy, mapping = aes(x= air_temp, y=(c_flux))) +
  geom_point() + geom_smooth(method = lm) + theme_bw()+
  labs(x="Air Temperature (°C)", y = expression(Carbon ~ Flux ~ (mmol ~ '/' ~ m^{2} ~ '/' ~ day)))

# Pearson's Correlation Test for CO2 flux and Air temperature 
cor.test(data_tidy$c_flux, data_tidy$air_temp)

# Linear model (Effect of Air Temperature on CO2 Flux) 
lm_overall <- lm(c_flux ~ air_temp, data = data_tidy)
summary(lm_overall)
``` 

## Analyze the effect of air temperature on CO2 flux (by habitat)

```{r}
# C Flux ~ Air temp (by Habitat)
# Scatterplot with estimated linear regression lines
ggplot() +
    geom_point(data = data_tidy, mapping = aes(x= air_temp, y=(c_flux), color = Habitat)) + 
    geom_smooth(data = data_tidy, mapping = aes(x= air_temp, y=(c_flux), color = Habitat), 
    method = lm, se =F) + theme_bw() +
  labs(x="Air Temperature (°C)", y = expression(Carbon ~ Flux ~ (mmol ~ '/' ~ m^{2} ~ '/' ~ day)))

# List all unique habitat types
unique(data_tidy$Habitat) 
 
## Create discrete data frames containing observations of each habitat type
pond <- data_tidy %>% filter(Habitat == "pond")
lake <- data_tidy %>% filter(Habitat == "lake")
lagoon <- data_tidy %>% filter(Habitat == "lagoon")
river <- data_tidy %>% filter(Habitat == "river")
salt_river <- data_tidy %>% filter(Habitat == "salt-river")

# Correlation test for each habitat type (* denotes significant p value for correlation)
cor.test(pond$c_flux, pond$air_temp) #p-value = 0.01328 *
cor.test(lake$c_flux, lake$air_temp) #p-value = 0.5811
cor.test(lagoon$c_flux, lagoon$air_temp) #p-value = 1.613e-13 *
cor.test(river$c_flux, river$air_temp) #p-value = 0.8745
cor.test(salt_river$c_flux, salt_river$air_temp) #p-value = 0.05199

# Linear Regression for significantly correlated habitat data (pond and lagoon)
pond_lm <- lm(c_flux ~ air_temp, data = pond)
lagoon_lm <- lm(c_flux ~ air_temp, data = lagoon)

## View summary data from linear models
summary(pond_lm)
summary(lagoon_lm)
```

